package com.example.blogandroidapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.blogandroidapp.dao.Persons;

import com.example.blogandroidapp.dao.PersonsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personsDaoConfig;

    private final PersonsDao personsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personsDaoConfig = daoConfigMap.get(PersonsDao.class).clone();
        personsDaoConfig.initIdentityScope(type);

        personsDao = new PersonsDao(personsDaoConfig, this);

        registerDao(Persons.class, personsDao);
    }
    
    public void clear() {
        personsDaoConfig.getIdentityScope().clear();
    }

    public PersonsDao getPersonsDao() {
        return personsDao;
    }

}
