package com.example.blogandroidapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERSONS.
 */
public class Persons {

    private Long PersonId;
    private String Name;
    private String City;

    public Persons() {
    }

    public Persons(Long PersonId) {
        this.PersonId = PersonId;
    }

    public Persons(Long PersonId, String Name, String City) {
        this.PersonId = PersonId;
        this.Name = Name;
        this.City = City;
    }

    public Long getPersonId() {
        return PersonId;
    }

    public void setPersonId(Long PersonId) {
        this.PersonId = PersonId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

}
